'use strict';
const $ = id => document.getElementById(id);
const tokenFromURL = new URLSearchParams(location.hash.slice(1)).get('token');
if (tokenFromURL) { sessionStorage.setItem('kaflow.token', tokenFromURL); history.replaceState(null, '', location.pathname); }
const token = sessionStorage.getItem('kaflow.token') || '';
const revisions = {metadata:0,groups:0,offsets:0};
const state = { session: '', metadata: null, topic: '', messages: [], view: 'topics', epoch: 0, read: 0 };
let profiles = [];
try { profiles = JSON.parse(localStorage.getItem('kaflow.profiles') || '[]'); if (!Array.isArray(profiles)) profiles = []; } catch { profiles = []; }
profiles=profiles.filter(p=>p&&typeof p.name==='string'&&typeof p.brokers==='string'&&typeof p.tls==='boolean'&&['none','plain','scram-sha-256','scram-sha-512'].includes(p.sasl));
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function note(text, error=false) { $('notice').textContent=text; $('notice').className='notice'+(error?' error':''); $('notice').hidden=!text; }
async function api(action, body={}) {
 const response=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({session:state.session,...body})});
 const result=await response.json(); if(!response.ok) throw new Error(result.error||'请求失败'); return result.data;
}
async function busy(button, fn) { if(button.disabled)return; const epoch=state.epoch; const old=button.textContent; button.disabled=true;button.textContent='处理中…';try{await fn()}catch(e){if(epoch===state.epoch)note(e.message,true)}finally{button.disabled=button.id==='disconnect'&&!state.session;button.textContent=old} }
function requireConnection(){if(!state.session){$('connectDialog').showModal();return false}return true}
function table(headers, rows){return '<div class="table-scroll"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table></div>'}
function empty(title,desc){return '<div class="empty"><div class="empty-icon">▤</div><h3>'+esc(title)+'</h3><p>'+esc(desc)+'</p></div>'}
function topics(){return Object.values(state.metadata?.Topics||{}).sort((a,b)=>a.Topic.localeCompare(b.Topic))}
function renderTopics(){
 const all=topics(), q=$('topicSearch').value.toLowerCase();const visible=all.filter(t=>(!t.IsInternal||$('showInternal').checked)&&t.Topic.toLowerCase().includes(q));
 $('listCount').textContent=visible.length+' 个 Topic';
 if(!state.session){$('topicList').innerHTML=empty('从连接你的集群开始','添加 Kafka 地址，查看 Topics、消息和消费组。')+'<div class="empty compact"><button id="emptyConnect" class="primary">＋ 添加连接</button></div>';$('emptyConnect').onclick=()=> $('connectDialog').showModal();return}
 if(!visible.length){$('topicList').innerHTML=empty('没有匹配的 Topic',all.length?'试试其他搜索词，或显示内部 Topic。':'创建你的第一个 Topic，开始发送消息。');return}
 $('topicList').innerHTML=table(['TOPIC 名称','分区','副本','状态',''],visible.map((t,i)=>{const parts=Object.values(t.Partitions||{}), bad=t.Err||parts.some(p=>p.Err||p.Leader<0||p.ISR.length<p.Replicas.length);return '<tr class="clickable" data-topic-index="'+i+'"><td><button class="text-button topic-name"><span class="topic-symbol">▤</span>'+esc(t.Topic)+'</button></td><td>'+parts.length+'</td><td>'+esc([...new Set(parts.map(p=>p.Replicas.length))].join(' / '))+'</td><td><span class="tag '+(bad?'warn':'')+'">'+(bad?'检查分区':t.IsInternal?'INTERNAL':'READY')+'</span></td><td class="muted">→</td></tr>'}).join(''));
 document.querySelectorAll('[data-topic-index]').forEach(el=>el.onclick=()=>selectTopic(visible[+el.dataset.topicIndex].Topic));
}
async function refresh(){
 if(!requireConnection())return;const epoch=state.epoch,revision=++revisions.metadata;const md=await api('metadata');if(epoch!==state.epoch||revision!==revisions.metadata)return;state.metadata=md;
 $('statTopics').textContent=topics().length;$('topicCount').textContent=topics().length;$('statBrokers').textContent=(md.Brokers||[]).length;$('statPartitions').textContent=topics().reduce((n,t)=>n+Object.keys(t.Partitions||{}).length,0);$('lastUpdated').textContent='更新于 '+new Date().toLocaleTimeString();renderTopics();renderBrokers();if(state.view==='groups')await renderGroups();
 if(state.topic&&!md.Topics?.[state.topic]){$('topicDetail').hidden=true;state.topic=''}
}
function renderBrokers(){const bs=state.metadata?.Brokers||[];$('brokersView').innerHTML=bs.length?table(['BROKER ID','HOST','PORT','RACK','ROLE'],bs.map(b=>'<tr><td>'+b.NodeID+'</td><td class="topic-name">'+esc(b.Host)+'</td><td>'+b.Port+'</td><td>'+esc(b.Rack||'—')+'</td><td><span class="tag">'+(b.NodeID===state.metadata.Controller?'CONTROLLER':'BROKER')+'</span></td></tr>').join('')):empty('暂无 Broker','连接集群后查看节点信息。')}
async function renderGroups(){if(!state.session){$('groupsView').innerHTML=empty('尚未连接','连接集群后查看消费组。');return}const epoch=state.epoch,revision=++revisions.groups;$('groupsView').innerHTML=empty('正在查询消费组','读取成员、提交位点和分区 Lag…');const data=await api('groups');if(epoch!==state.epoch||revision!==revisions.groups)return;const groups=Object.values(data||{});if(!groups.length){$('groupsView').innerHTML=empty('暂无消费组','集群中尚未发现消费组。');return}
 $('groupsView').innerHTML=groups.map(g=>{const rows=[];for(const [topic,parts]of Object.entries(g.Lag||{})){for(const [p,l]of Object.entries(parts)){rows.push('<tr><td class="topic-name">'+esc(topic)+'</td><td>'+esc(p)+'</td><td>'+esc(l.Commit?.At??'—')+'</td><td>'+esc(l.End?.Offset??'—')+'</td><td>'+esc(l.Err?l.Err:BigInt(l.Lag)<0n?'未提交':l.Lag)+'</td></tr>')}}return '<div class="detail-heading"><div><h2>'+esc(g.Group)+'</h2><span class="muted">'+esc(g.State)+' · '+(g.Members||[]).length+' 个成员</span></div><span class="tag">'+esc(g.Error||g.DescribeErr||g.FetchErr?'查询异常':'CONSUMER GROUP')+'</span></div>'+ (g.DescribeErr||g.FetchErr?'<p class="hint error">'+esc(g.DescribeErr||g.FetchErr)+'</p>':'')+(rows.length?table(['TOPIC','PARTITION','COMMITTED','END OFFSET','LAG'],rows.join('')):empty('暂无已提交位点','该组没有可展示的分区位点。'))}).join('');
}
async function selectTopic(name){state.topic=name;state.messages=[];state.read++;$('detailName').textContent=name;$('topicDetail').hidden=false;$('messageList').innerHTML=empty('准备读取','选择起点和分区，点击读取消息。');const parts=Object.keys(state.metadata.Topics[name].Partitions||{}).sort((a,b)=>a-b);$('readPartition').innerHTML='<option value="">全部分区</option>'+parts.map(p=>'<option>'+p+'</option>').join('');$('producePartition').innerHTML='<option value="">自动分区</option>'+parts.map(p=>'<option>'+p+'</option>').join('');$('topicDetail').scrollIntoView({behavior:'smooth',block:'start'});try{await loadOffsets()}catch(e){note(e.message,true)}}
async function loadOffsets(){const topic=state.topic,epoch=state.epoch,revision=++revisions.offsets;const data=await api('offsets',{topic});if(topic!==state.topic||epoch!==state.epoch||revision!==revisions.offsets)return;const parts=state.metadata.Topics[topic].Partitions||{};$('partitionsTab').innerHTML=table(['PARTITION','LEADER','REPLICAS / ISR','START OFFSET','END OFFSET','OFFSET 跨度'],Object.values(parts).sort((a,b)=>a.Partition-b.Partition).map(p=>{const start=data.start[p.Partition]?.Offset,end=data.end[p.Partition]?.Offset;return '<tr><td>'+p.Partition+'</td><td>'+p.Leader+'</td><td>'+esc(p.Replicas.join(', '))+' / '+esc(p.ISR.join(', '))+'</td><td>'+esc(start)+'</td><td>'+esc(end)+'</td><td>'+esc(BigInt(end)-BigInt(start))+'</td></tr>'}).join(''))+'<p class="hint">Offset 跨度不等于消息条数：压缩、事务和删除可能产生空洞。</p>'}
function renderMessages(){const q=$('messageSearch').value.toLowerCase();const rows=state.messages.map((m,i)=>({m,i})).filter(({m})=>((m.key||'')+' '+(m.value||'')).toLowerCase().includes(q));$('messageList').innerHTML=rows.length?table(['PARTITION','OFFSET','TIME','KEY','VALUE'],rows.map(({m,i})=>'<tr class="clickable" data-record="'+i+'"><td>'+m.partition+'</td><td><button class="text-button">'+esc(m.offset)+'</button></td><td>'+new Date(m.timestamp).toLocaleTimeString()+'</td><td class="message-value">'+esc(m.key??'null')+'</td><td class="message-value">'+esc(m.value??'null (tombstone)')+'</td></tr>').join('')):empty('没有匹配的消息','当前范围可能为空，或消息已被压缩/清理。');document.querySelectorAll('[data-record]').forEach(el=>el.onclick=()=>showRecord(state.messages[+el.dataset.record]))}
function pretty(s){if(s===null)return 'null';try{return JSON.stringify(JSON.parse(s),null,2)}catch{return s}}
function showRecord(m){$('recordMeta').textContent='Partition '+m.partition+' · Offset '+m.offset+' · '+new Date(m.timestamp).toLocaleString();$('recordKey').textContent=m.key??'null';$('recordValue').textContent=pretty(m.value);$('recordHeaders').textContent=JSON.stringify(m.headers,null,2);$('recordRaw').textContent=JSON.stringify({key:m.keyBase64,value:m.valueBase64},null,2);$('copyValue').onclick=()=>busy($('copyValue'),async()=>{await navigator.clipboard.writeText(m.value??'null');note('Value 已复制')});$('recordDialog').showModal()}
function saveProfiles(){localStorage.setItem('kaflow.profiles',JSON.stringify(profiles));renderProfiles()}
function renderProfiles(){$('savedProfiles').innerHTML='<option value="">新建连接</option>'+profiles.map((p,i)=>'<option value="'+i+'">'+esc(p.name)+'</option>').join('')}
const skipHostnameLabel=document.createElement('label');skipHostnameLabel.id='skipHostnameLabel';skipHostnameLabel.className='check';skipHostnameLabel.hidden=true;skipHostnameLabel.innerHTML='<input id="skipHostnameVerify" type="checkbox">关闭 TLS 主机名校验（仅兼容内部证书）';$('saveProfile').closest('label').before(skipHostnameLabel);
function authVisibility(){$('authFields').hidden=$('sasl').value==='none';$('tlsFields').hidden=!$('tls').checked;skipHostnameLabel.hidden=!$('tls').checked}
$('savedProfiles').onchange=()=>{const p=profiles[$('savedProfiles').value];for(const id of ['username','password','ca','cert','privateKey'])$(id).value='';$('skipHostnameVerify').checked=false;if(p){$('profileName').value=p.name;$('brokers').value=p.brokers;$('tls').checked=p.tls;$('sasl').value=p.sasl;$('skipHostnameVerify').checked=Boolean(p.skipHostnameVerify)}else{$('profileName').value='';$('brokers').value='';$('tls').checked=false;$('sasl').value='none'}authVisibility()};
$('forgetProfile').onclick=()=>{if($('savedProfiles').value!==''){profiles.splice(+$('savedProfiles').value,1);saveProfiles();note('已移除保存的连接')}};
$('sasl').onchange=authVisibility;$('tls').onchange=authVisibility;
$('connectionButton').onclick=()=> $('connectDialog').showModal();
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('connectForm').onsubmit=e=>{e.preventDefault();busy($('connectSubmit'),async()=>{ $('connectError').textContent='';try{const config={brokers:$('brokers').value.trim(),tls:$('tls').checked,sasl:$('sasl').value,username:$('username').value,password:$('password').value,ca:$('ca').value,cert:$('cert').value,privateKey:$('privateKey').value,skipHostnameVerify:$('skipHostnameVerify').checked};const result=await api('connect',{connection:config});const oldSession=state.session;state.session=result.session;state.epoch++;state.topic='';state.messages=[];$('topicDetail').hidden=true;state.metadata=null;renderTopics();if(oldSession)api('disconnect',{session:oldSession}).catch(()=>{});$('connectionName').textContent=$('profileName').value;$('connectionAddress').textContent=config.brokers;$('statusDot').className='status-dot green';$('statConnection').textContent='已连接';$('disconnect').disabled=false;
 if($('saveProfile').checked){const profile={name:$('profileName').value,brokers:config.brokers,tls:config.tls,sasl:config.sasl,skipHostnameVerify:config.skipHostnameVerify};profiles=profiles.filter(p=>p.name!==profile.name);profiles.push(profile);try{saveProfiles()}catch{note('连接成功，但浏览器禁止保存配置',true)}}
 for(const id of ['password','privateKey','cert','ca'])$(id).value='';$('connectDialog').close();note('已连接 '+$('profileName').value);await refresh();}catch(err){if($('connectDialog').open)$('connectError').textContent=err.message;else note(err.message,true)}})};
$('disconnect').onclick=()=>busy($('disconnect'),async()=>{const oldSession=state.session;await api('disconnect');if(state.session!==oldSession)return;state.session='';state.epoch++;state.metadata=null;state.topic='';state.messages=[];$('topicDetail').hidden=true;$('connectionName').textContent='尚未连接';$('connectionAddress').textContent='添加你的 Kafka 集群';$('statusDot').className='status-dot';$('statConnection').textContent='离线';for(const id of ['statTopics','statBrokers','statPartitions'])$(id).textContent='—';$('topicCount').textContent='0';$('lastUpdated').textContent='等待连接集群';renderTopics();renderBrokers();$('groupsView').innerHTML=empty('尚未连接','连接集群后查看消费组。');note('连接已断开，凭据已从会话释放')});
$('refresh').onclick=()=>busy($('refresh'),refresh);
$('topicSearch').oninput=renderTopics;$('showInternal').onchange=renderTopics;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=async()=>{const epoch=state.epoch;state.view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));for(const v of ['topics','groups','brokers'])$(v+'View').hidden=v!==state.view;const names={topics:'Topics',groups:'消费组',brokers:'Brokers'};$('pageTitle').textContent=names[state.view];$('breadcrumb').textContent=names[state.view];$('pageDescription').textContent={topics:'浏览数据流，找到每一条消息。',groups:'查看消费进度与积压，了解数据流向。',brokers:'查看集群节点与 Controller 信息。'}[state.view];$('createTopic').hidden=state.view!=='topics';try{if(state.view==='groups')await renderGroups();if(state.view==='brokers')renderBrokers()}catch(e){if(epoch!==state.epoch)return;$('groupsView').innerHTML=empty('查询失败',e.message);note(e.message,true)}});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('messagesTab').hidden=b.dataset.tab!=='messages';$('partitionsTab').hidden=b.dataset.tab!=='partitions'});
$('closeDetail').onclick=()=>{$('topicDetail').hidden=true;state.topic='';state.read++};
$('readMode').onchange=()=>{$('offsetLabel').hidden=$('readMode').value!=='offset'};
$('loadMessages').onclick=()=>busy($('loadMessages'),async()=>{const epoch=state.epoch,topic=state.topic,read=++state.read;const result=await api('messages',{topic,mode:$('readMode').value,partition:$('readPartition').value===''?null:+$('readPartition').value,offset:$('readOffset').value,limit:+$('readLimit').value});if(epoch!==state.epoch||topic!==state.topic||read!==state.read)return;state.messages=result.messages;$('readHint').textContent='本次读取 '+result.messages.length+' 条 · '+(result.partial?'达到时间或大小限制，结果可能不完整。':result.limited?'已达条数上限，可按分区或 Offset 继续读取。':'快照读取完成。')+' 不提交消费位点。';renderMessages();await loadOffsets()});
$('messageSearch').oninput=renderMessages;
$('exportMessages').onclick=()=>{if(!state.messages.length){note('请先读取消息');return}const url=URL.createObjectURL(new Blob([JSON.stringify({topic:state.topic,messages:state.messages},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=state.topic+'-messages.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
function openForm(id){$(id).querySelector('.error').textContent='';$(id).showModal()}
$('createTopic').onclick=()=>{if(requireConnection())openForm('createDialog')};
function submitForm(id,fn){$(id).onsubmit=e=>{e.preventDefault();const form=$(id),button=form.querySelector('button:not([type="button"])');busy(button,async()=>{form.querySelector('.error').textContent='';try{await fn();}catch(e){form.querySelector('.error').textContent=e.message}})}}
submitForm('createForm',async()=>{const topic=$('newTopicName').value;await api('create',{topic,partitions:+$('newPartitions').value,replicas:+$('newReplicas').value});$('createDialog').close();note('Topic '+topic+' 已创建');await refresh()});
$('produce').onclick=()=>{$('produceTarget').textContent=state.topic;openForm('produceDialog')};
$('tombstone').onchange=()=>{$('produceValue').disabled=$('tombstone').checked};
$('formatJSON').onclick=()=>{try{$('produceValue').value=JSON.stringify(JSON.parse($('produceValue').value),null,2);$('produceForm').querySelector('.error').textContent=''}catch{$('produceForm').querySelector('.error').textContent='Value 不是有效 JSON；也可以直接发送普通文本。'}};
submitForm('produceForm',async()=>{let headers=[];try{headers=JSON.parse($('produceHeaders').value||'[]')}catch{throw new Error('Headers 必须是 JSON 数组')}if(!Array.isArray(headers)||headers.some(h=>!h||typeof h.key!=='string'||typeof h.value!=='string'))throw new Error('Headers 格式：[{"key":"名称","value":"内容"}]');const result=await api('produce',{topic:state.topic,partition:$('producePartition').value===''?null:+$('producePartition').value,key:$('produceKey').value||null,value:$('tombstone').checked?null:$('produceValue').value,headers});$('produceDialog').close();note('发送成功 · Partition '+result.partition+' · Offset '+result.offset);await loadOffsets()});
$('deleteTopic').onclick=()=>{$('deleteTarget').textContent=state.topic;$('deleteConfirm').value='';openForm('deleteDialog')};
submitForm('deleteForm',async()=>{await api('delete',{topic:state.topic,confirm:$('deleteConfirm').value});$('deleteDialog').close();$('topicDetail').hidden=true;state.topic='';note('Topic 删除请求已确认');await refresh()});
renderProfiles();renderTopics();renderBrokers();if(!token)note('请通过程序启动时显示的完整地址打开页面。',true);
